#!/usr/bin/env bash

if [[ -z "$1" ]]; then
  printf "Search query: "; 
  query=$( echo | rofi -dmenu -p "Search YT Video" -l 0 )
else
	query="$1"
fi

query="${query// /+}"
echo "$query"

# YT_API_KEY location
YT_API_KEY="$( cat "${HOME}"/.api_keys/YT_API_KEY )"
urlstring="https://www.googleapis.com/youtube/v3/search?part=snippet&q=${query}&type=video&maxResults=15&key=${YT_API_KEY}"

mpv "https://$( curl -s "${urlstring}" \
	| jq -r '.items[] | "\(.snippet.channelTitle) => \(.snippet.title) => youtu.be/\(.id.videoId)"' \
	| rofi -dmenu -i -p 'Select Video' -l 15 \
	| awk '{print $NF}' \
)" --ontop=yes --geometry=25%-10+10
